# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0003_auto_20160321_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
