# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0004_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('doctorAvailability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorAvailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Patient')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('nurseAvailability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.NurseAvailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Patient')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='doctorappointment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='nurseappointment',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='doctorAvailability',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nurseappointment',
            name='nurseAvailability',
        ),
        migrations.RemoveField(
            model_name='nurseappointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='nurseappointment',
            name='status',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctorBooking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorBooking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseappointment',
            name='nurseBooking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.NurseBooking'),
            preserve_default=False,
        ),
    ]
