# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0005_auto_20160328_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbooking',
            name='details',
        ),
    ]
