# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('staffNo', models.CharField(max_length=20)),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.TimeField()),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Doctor')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('staffNo', models.CharField(max_length=20)),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.TimeField()),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('nurseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Nurse')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('NHS_No', models.CharField(max_length=20)),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=20)),
                ('deptName', models.CharField(max_length=50)),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deliveryStatus', models.BooleanField()),
                ('paymentStatus', models.BooleanField()),
                ('doctorAppointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorAppointment')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('doctorAppointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorAppointment')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.CharField(max_length=20)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery')),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('surgeryAdmin', 'surgeryAdmin'), ('doctor', 'doctor'), ('nurse', 'nurse'), ('patient', 'patient'), ('pharmacy', 'pharmacy')], max_length=15)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('surgery_specific', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='surgeryadmin',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.UserProfile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='specializedFacility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.SpecializedFacility'),
        ),
        migrations.AddField(
            model_name='referral',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.UserProfile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='patient',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.UserProfile'),
        ),
        migrations.AddField(
            model_name='nurseavailability',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='nurseappointment',
            name='nurseAvailability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.NurseAvailability'),
        ),
        migrations.AddField(
            model_name='nurseappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Patient'),
        ),
        migrations.AddField(
            model_name='nurseappointment',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.UserProfile'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctorAvailability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorAvailability'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Patient'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.UserProfile'),
        ),
    ]
