# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0010_auto_20160407_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='fixedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='fixedTime',
            field=models.TimeField(null=True),
        ),
    ]
