# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurseavailability',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nurseavailability',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
