# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgeriesOnline', '0007_auto_20160328_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=32)),
                ('charge_date', models.DateTimeField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Prescription')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.Surgery')),
            ],
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctorBooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.DoctorBooking'),
        ),
        migrations.AlterField(
            model_name='nurseappointment',
            name='nurseBooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeriesOnline.NurseBooking'),
        ),
    ]
